version: 3
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    restart: on-failure
    depends_on:
      - "postgres"
      - "redis"
    networks:
      - app-network

  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_USERNAME=
      - POSTGRESQL_DATABASE=
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - app-network
    # volumes:
    #   - ./postgres-data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=
    ports:
      - 6379:6379
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
